language: python
sudo: false

jobs:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
    - os: linux
      python: 3.9

install:
  - pip install poetry
  - poetry install

script:
  - poetry run nosetests
  - poetry run flake8 sphinxcontrib

after_script:
  - codecov

