language: python
sudo: false

jobs:
  include:
    - os: linux
      python: 2.7
      env: TOXENV=py27
    - os: linux
      python: 3.6
      env: TOXENV=py36
    - os: linux
      python: 3.7
      env: TOXENV=py37
    - os: linux
      python: 3.8
      env: TOXENV=py38
    - os: linux
      python: 3.9
      env: TOXENV=py39

install:
  - pip install tox codecov

script:
  - tox -c tox.ini 

after_script:
  - codecov

